apiVersion: v1
kind: ConfigMap
metadata:
  name: debian-config
  namespace: debian
data:
  ENV: "prod"
  PORT: "8080"
  PINECONE_INDEX_NAME: "debian-rag"
  PINECONE_DIMENSION: "128"
  BIGQUERY_DATASET: "debian_analytics"
