apiVersion: v1
kind: Secret
metadata:
  name: debian-secrets
  namespace: debian
type: Opaque
stringData:
  DB_CLIENT_ID: "replace-me"
  DB_API_KEY: "replace-me"
  PINECONE_API_KEY: "replace-me"
  DATABRICKS_HOST: "replace-me"
  DATABRICKS_TOKEN: "replace-me"
